using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class giro : MonoBehaviour
{
    public float rotationSpeed = 10f; // Velocidad de rotaci贸n en grados por segundo

    // Update es llamado una vez por frame
    void Update()
    {
        // Obtener la rotaci贸n actual del objeto
        Vector3 rotation = transform.rotation.eulerAngles;

        // Calcular la nueva rotaci贸n del objeto
        float newRotation = rotation.y + rotationSpeed * Time.deltaTime;

        // Aplicar la rotaci贸n al objeto
        transform.rotation = Quaternion.Euler(0, newRotation, 0);
    }
}
